checkpoints:
  - model_name: ViT-B-32
    pretrained: laion2b_s34b_b79k
    tag: vit_b32_laion2b
  - model_name: ViT-B-16
    pretrained: datacomp_xl_s13b_b90k
    tag: vit_b16_datacomp
  - model_name: ViT-L-14
    pretrained: openai
    tag: vit_l14_openai
