job_name: week5_openclip_eval_single_node
nproc_per_node: 2
metadata_csv: data/bootstrap_flickr30k/metadata.csv
prompt_config: data/bootstrap_flickr30k/prompt_config.json
model_name: ViT-B-32
pretrained: laion2b_s34b_b79k
